# Generated by Django 3.2.3 on 2021-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_auto_20210715_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
